services:
  fast:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: fast_prod
    container_name: fast_prod
    restart: always
    command: 'uvicorn app.main:app --workers 4 --host 0.0.0.0 --port 8000'
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db


  db:
    image: postgres:17-alpine
    container_name: psgr
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db

  nginx:
    build: nginx
    ports:
      - '80:80'
    depends_on:
      - fast


volumes:
  postgres_data: