services:
  fast:
    build: .
    image: fast
    container_name: fast
    restart: always
    command: 'uvicorn app.main:app --host 0.0.0.0'
    env_file:
      - .env
    volumes:
      - .:/home/fast/
    ports:
      - '8000:8000'
    depends_on:
      - db


  db:
    image: postgres:17-alpine
    container_name: psgr
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db


volumes:
  postgres_data: